version: "3"

services:
  app:
    build: app
    volumes:
      - ./app:/app

  test-db:
    build: test-db
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 0
      TZ: Asia/Tokyo

volumes:
  mysql_data: