version: "3"

services:
  test-db:
    build: test-db
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 0
      TZ: Asia/Tokyo

volumes:
  mysql_data: